lambda debug

diff --git a/.github/actions/deploy/action.yml b/.github/actions/deploy/action.yml
--- a/.github/actions/deploy/action.yml
+++ b/.github/actions/deploy/action.yml
@@ -55,8 +55,22 @@ runs:
         echo "Triggering lambda function ..."
         VERSION="${{ env.NEW_VERSION }}"
         PAYLOAD=$(jq -n --arg version "$VERSION" '{deployed_version:$version}' | base64)
-        aws lambda invoke --function-name AutoRunStartupScript --payload "$PAYLOAD" response.json
-        cat response.json
+        RETRIES=5
+        for i in $(seq 1 $RETRIES); do
+          RESPONSE=$(aws lambda invoke --function-name AutoRunStartupScript --payload "$PAYLOAD" response.json)
+          if [ [$? -eq 0] ]; then
+            echo "Lambda function triggered successfully"
+            cat response.json
+            break
+          else
+            echo "Failed to trigger lambda function. Retrying..."
+            if [[ $i -eq $RETRIES ]]; then
+              echo "Failed to trigger lambda function after $RETRIES retries"
+              exit 1
+            fi
+            sleep 5
+          fi
+        done
       shell: bash
 
     - name: Wait for the deployed version to update
