Deployment verification

diff --git a/.github/workflows/deploy-develop.yml b/.github/workflows/deploy-develop.yml
--- a/.github/workflows/deploy-develop.yml
+++ b/.github/workflows/deploy-develop.yml
@@ -34,6 +34,37 @@ jobs:
           aws-role: arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL
           parameter-path: /application/web/${{ matrix.service }}/docker_images
 
+      - name: Update deployed version in parameter store
+        run: |
+          IMAGE_TAG=$(aws ssm get-parameter --name "/application/web/${{ matrix.service}}/docker_images" --query "Parameter.Value" --output text)
+          aws ssm put-parameter --name "/application/web/${{ matrix.service}}/deployed_version" --value "$IMAGE_TAG" --type "String" --overwrite
+        env:
+          AWS_REGION: eu-west-2
+
+      - name: Verify Deployment
+        run: |
+          IMAGE_TAG=$(aws ssm get-parameter --name "/application/web/${{ matrix.service}}/docker_images" --query "Parameter.Value" --output text)
+          
+          for i in {1..10}; do
+          DEPLOYED_VERSION=$(aws ssm get-parameter --name "/application/web/${{ matrix.service}}/deployed_version" --query "Parameter.Value" --output text || echo "No version found")
+
+          if [["$DEPLOYED_VERSION" == "$IMAGE_TAG" ]]; then
+            echo "  ✅ Deployment successful! Version: $DEPLOYED_VERSION"
+            exit 0
+          fi
+            echo "  ⏳ Waiting for deployment to complete... Checking again in 10 seconds."
+            sleep 10
+          done
+
+          echo "  ❌ Deployment verification failed. The deployment version did not update in time"
+          exit 1
+        env:
+          AWS_REGION: eu-west-2
+          
+          
+          
+
+
   # test:
   #   runs-on: ubuntu-latest
   #   needs:
@@ -44,3 +75,5 @@ jobs:
   #     - uses: actions/checkout@v4
   #     - name: Run tests
   #       run: gh workflow run manual.yml --repo nationalarchives/ds-tna-website-tests --raw-field domain=https://dev-www.nationalarchives.gov.uk --raw-field notify-slack=true --raw-field description="$(git log -1 --pretty=%B | sed '/./,$!d' | sed '/^$/d' | sed 's/^/> /')"
+
+       
